version: "3.8"
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  test:
    build: 
      dockerfile: Dockerfile
      context: .
    command: npm run test
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"